### ISSUE TITLE
citrix_netscaler date format issue (SC4S v2.32.6)

### ISSUE THREAD

**Issue by davidbattyJDS** [splunk/splunk-connect-for-syslog#1778] opened 2022-08-08 06:01 UTC
As part of upgrade during regression testing of Citrix found data not being parsed correctly for August only.

**Test Data (for each month)**
echo '<12> 01/13/2022:01:01:01 GMT netscaler ABC-D : SSLVPN HTTPREQUEST 1234567 : Context wbg_netscaler_date_t002@192.0.2.1 - SessionId: 12345- example.com User username : Group(s) groupname : Vserver a1b2:c3d4:e5f6:a7b8:c9d0:e1f2:a3b4:c5d6:123 - 01/01/2001:01:01:01 GMT GET file/path.gif - - '> /dev/udp/127.0.0.1/9514
echo '<12> 02/13/2022:01:01:01 GMT netscaler ABC-D : SSLVPN HTTPREQUEST 1234567 : Context wbg_netscaler_date_t002@192.0.2.1 - SessionId: 12345- example.com User username : Group(s) groupname : Vserver a1b2:c3d4:e5f6:a7b8:c9d0:e1f2:a3b4:c5d6:123 - 01/01/2001:01:01:01 GMT GET file/path.gif - - '> /dev/udp/127.0.0.1/9514
echo '<12> 03/13/2022:01:01:01 GMT netscaler ABC-D : SSLVPN HTTPREQUEST 1234567 : Context wbg_netscaler_date_t002@192.0.2.1 - SessionId: 12345- example.com User username : Group(s) groupname : Vserver a1b2:c3d4:e5f6:a7b8:c9d0:e1f2:a3b4:c5d6:123 - 01/01/2001:01:01:01 GMT GET file/path.gif - - '> /dev/udp/127.0.0.1/9514
echo '<12> 04/13/2022:01:01:01 GMT netscaler ABC-D : SSLVPN HTTPREQUEST 1234567 : Context wbg_netscaler_date_t002@192.0.2.1 - SessionId: 12345- example.com User username : Group(s) groupname : Vserver a1b2:c3d4:e5f6:a7b8:c9d0:e1f2:a3b4:c5d6:123 - 01/01/2001:01:01:01 GMT GET file/path.gif - - '> /dev/udp/127.0.0.1/9514
echo '<12> 05/13/2022:01:01:01 GMT netscaler ABC-D : SSLVPN HTTPREQUEST 1234567 : Context wbg_netscaler_date_t002@192.0.2.1 - SessionId: 12345- example.com User username : Group(s) groupname : Vserver a1b2:c3d4:e5f6:a7b8:c9d0:e1f2:a3b4:c5d6:123 - 01/01/2001:01:01:01 GMT GET file/path.gif - - '> /dev/udp/127.0.0.1/9514
echo '<12> 06/13/2022:01:01:01 GMT netscaler ABC-D : SSLVPN HTTPREQUEST 1234567 : Context wbg_netscaler_date_t002@192.0.2.1 - SessionId: 12345- example.com User username : Group(s) groupname : Vserver a1b2:c3d4:e5f6:a7b8:c9d0:e1f2:a3b4:c5d6:123 - 01/01/2001:01:01:01 GMT GET file/path.gif - - '> /dev/udp/127.0.0.1/9514
echo '<12> 07/13/2022:01:01:01 GMT netscaler ABC-D : SSLVPN HTTPREQUEST 1234567 : Context wbg_netscaler_date_t002@192.0.2.1 - SessionId: 12345- example.com User username : Group(s) groupname : Vserver a1b2:c3d4:e5f6:a7b8:c9d0:e1f2:a3b4:c5d6:123 - 01/01/2001:01:01:01 GMT GET file/path.gif - - '> /dev/udp/127.0.0.1/9514
echo '<12> 08/13/2022:01:01:01 GMT netscaler ABC-D : SSLVPN HTTPREQUEST 1234567 : Context wbg_netscaler_date_t002@192.0.2.1 - SessionId: 12345- example.com User username : Group(s) groupname : Vserver a1b2:c3d4:e5f6:a7b8:c9d0:e1f2:a3b4:c5d6:123 - 01/01/2001:01:01:01 GMT GET file/path.gif - - '> /dev/udp/127.0.0.1/9514
echo '<12> 09/13/2022:01:01:01 GMT netscaler ABC-D : SSLVPN HTTPREQUEST 1234567 : Context wbg_netscaler_date_t002@192.0.2.1 - SessionId: 12345- example.com User username : Group(s) groupname : Vserver a1b2:c3d4:e5f6:a7b8:c9d0:e1f2:a3b4:c5d6:123 - 01/01/2001:01:01:01 GMT GET file/path.gif - - '> /dev/udp/127.0.0.1/9514
echo '<12> 10/13/2022:01:01:01 GMT netscaler ABC-D : SSLVPN HTTPREQUEST 1234567 : Context wbg_netscaler_date_t002@192.0.2.1 - SessionId: 12345- example.com User username : Group(s) groupname : Vserver a1b2:c3d4:e5f6:a7b8:c9d0:e1f2:a3b4:c5d6:123 - 01/01/2001:01:01:01 GMT GET file/path.gif - - '> /dev/udp/127.0.0.1/9514
echo '<12> 11/13/2022:01:01:01 GMT netscaler ABC-D : SSLVPN HTTPREQUEST 1234567 : Context wbg_netscaler_date_t002@192.0.2.1 - SessionId: 12345- example.com User username : Group(s) groupname : Vserver a1b2:c3d4:e5f6:a7b8:c9d0:e1f2:a3b4:c5d6:123 - 01/01/2001:01:01:01 GMT GET file/path.gif - - '> /dev/udp/127.0.0.1/9514
echo '<12> 12/13/2022:01:01:01 GMT netscaler ABC-D : SSLVPN HTTPREQUEST 1234567 : Context wbg_netscaler_date_t002@192.0.2.1 - SessionId: 12345- example.com User username : Group(s) groupname : Vserver a1b2:c3d4:e5f6:a7b8:c9d0:e1f2:a3b4:c5d6:123 - 01/01/2001:01:01:01 GMT GET file/path.gif - - '> /dev/udp/127.0.0.1/9514

Result for all months except August correct i.e. converting mm/dd/yyyy to dd/mm/yyyy
![image](https://user-images.githubusercontent.com/16346176/183348868-bc804c3f-02e4-474c-981e-07cc92e69ff9.png)

Further tests confirm this is only happening for August

**Correct**:
echo '<12> 07/05/2022:01:01:01 GMT netscaler ABC-D : SSLVPN HTTPREQUEST 1234567 : Context wbg_netscaler_date_t006@192.0.2.1 - SessionId: 12345- example.com User username : Group(s) groupname : Vserver a1b2:c3d4:e5f6:a7b8:c9d0:e1f2:a3b4:c5d6:123 - 01/01/2001:01:01:01 GMT GET file/path.gif - - '> /dev/udp/127.0.0.1/9514

**Incorrect**:
echo '<12> 08/05/2022:01:01:01 GMT netscaler ABC-D : SSLVPN HTTPREQUEST 1234567 : Context wbg_netscaler_date_t006@192.0.2.1 - SessionId: 12345- example.com User username : Group(s) groupname : Vserver a1b2:c3d4:e5f6:a7b8:c9d0:e1f2:a3b4:c5d6:123 - 01/01/2001:01:01:01 GMT GET file/path.gif - - '> /dev/udp/127.0.0.1/9514

**Correct**:
echo '<12> 09/05/2022:01:01:01 GMT netscaler ABC-D : SSLVPN HTTPREQUEST 1234567 : Context wbg_netscaler_date_t006@192.0.2.1 - SessionId: 12345- example.com User username : Group(s) groupname : Vserver a1b2:c3d4:e5f6:a7b8:c9d0:e1f2:a3b4:c5d6:123 - 01/01/2001:01:01:01 GMT GET file/path.gif - - '> /dev/udp/127.0.0.1/9514

![image](https://user-images.githubusercontent.com/16346176/183349512-b41f0d67-a667-44eb-8c3b-6fd461c3795f.png)

**Comment by davidbattyJDS** [comment] 2022-08-09 01:20
Today the behaviour is different (tested on 3 environments with the following data)

**Correct**:
echo '<12> 07/05/2022:01:01:01 GMT netscaler ABC-D : SSLVPN HTTPREQUEST 1234567 : Context wbg_netscaler_date_t008@192.0.2.1 - SessionId: 12345- example.com User username : Group(s) groupname : Vserver a1b2:c3d4:e5f6:a7b8:c9d0:e1f2:a3b4:c5d6:123 - 01/01/2001:01:01:01 GMT GET file/path.gif - - '> /dev/udp/xxxxx/514

**Correct**:
echo '<12> 08/05/2022:01:01:01 GMT netscaler ABC-D : SSLVPN HTTPREQUEST 1234567 : Context wbg_netscaler_date_t008@192.0.2.1 - SessionId: 12345- example.com User username : Group(s) groupname : Vserver a1b2:c3d4:e5f6:a7b8:c9d0:e1f2:a3b4:c5d6:123 - 01/01/2001:01:01:01 GMT GET file/path.gif - - '> /dev/udp/xxxxx/514

**Incorrect**:
echo '<12> 09/05/2022:01:01:01 GMT netscaler ABC-D : SSLVPN HTTPREQUEST 1234567 : Context wbg_netscaler_date_t008@192.0.2.1 - SessionId: 12345- example.com User username : Group(s) groupname : Vserver a1b2:c3d4:e5f6:a7b8:c9d0:e1f2:a3b4:c5d6:123 - 01/01/2001:01:01:01 GMT GET file/path.gif - - '> /dev/udp/xxxxx/514

![image](https://user-images.githubusercontent.com/16346176/183541888-29f43b6c-eac4-46ce-ae41-48924a8ba26e.png)

**Comment by rjha-splunk** [comment] 2022-08-09 09:24
We will check this and get back.

**Comment by rjha-splunk** [comment] 2022-08-18 13:00
This looks like some issue with your system, i tested the same in our lab and we couldn't reproduce it
![Screenshot 2022-08-18 at 14 59 22](https://user-images.githubusercontent.com/90039710/185400931-3b6f6e6e-7b9d-4e2b-a8fc-5dab89f675cf.png)
![Screenshot 2022-08-18 at 14 56 55](https://user-images.githubusercontent.com/90039710/185400944-7d0390f9-4a39-442a-ab67-e11dca2eb61c.png)
.

**Comment by rjha-splunk** [comment] 2022-08-30 10:21
As pointed above we could not replicate the issue , closing the ticket.

**Closed by rjha-splunk** 2022-08-30 10:21 UTC
Labels: bug
