### ISSUE TITLE
F5 BigIP CROND events wrongly assigned as VMWare

### ISSUE THREAD

**Issue by Jo-Ng** [splunk/splunk-connect-for-syslog#1969] opened 2023-01-05 11:35 UTC
Detail: Podman 3.0.1 / RHEL 8.6
SC4S: 2.43.0
CRON events been identified as “sc4s_product=vsphere” / sourctype=“vmware:esxlog:crond” instead of BigIP events
Sample as below
 
![image](https://user-images.githubusercontent.com/84378190/210770832-62c2e898-7e4e-4a6c-aaee-0211a589067d.png)

Below the event description
 
![image](https://user-images.githubusercontent.com/84378190/210770895-40758217-aa7e-4337-babf-2d2a59c11efc.png)

The CROND job from BigIP shall not go to VMWare CROND work.
Attached the export of the events for reference.

[F5_VMWare.csv](https://github.com/splunk/splunk-connect-for-syslog/files/10351750/F5_VMWare.csv)

**Comment by rjha-splunk** [comment] 2023-01-05 13:09
can you please explain from when you started seeing it , or it was always like that, a raw anonymised sample will be helpful.

**Comment by rjha-splunk** [comment] 2023-01-05 14:41
The event attached is after processing , can you capture pcap and share it to me either over slack(external community) or open it using wireshark, anonymize and send it , you can ask PS person to reach me if he has sample.

**Comment by Jo-Ng** [comment] 2023-01-09 03:54
Rahul,That an issue to attached pcap to open forum or public storage area.Any alternative that I could upload to Splunk end example open support case?Raven,Possible provide some info to Rahul?Regard,JomonOn 5 Jan 2023, at 22:41, Rahul Jha ***@***.***> wrote:﻿
The event attached is after processing , can you capture pcap and share it to me either over slack(external community) or open it using wireshark, anonymize and send it , you can ask PS person to reach me if he has sample.

**Comment by Jo-Ng** [comment] 2023-01-09 05:49
Hope this pcap export have info you needed, else pls provide a secure place that I could upload the pcap file, example: Splunk Support portal

[brocade_ontab.csv](https://github.com/splunk/splunk-connect-for-syslog/files/10370547/brocade_ontab.csv)

**Comment by rjha-splunk** [comment] 2023-01-09 07:48
Please feel free to open a support case and mention this github issue

**Comment by Jo-Ng** [comment] 2023-01-09 09:34
Splunk support case 3134271. pcap uploaded

**Comment by rjha-splunk** [comment] 2023-01-09 16:35
Unfortunately here we need to write the program and sourceagain using post-filter 
```
application app-bigip-postfilter[sc4s-postfilter] {
 filter {
        host("test*" type(glob))
       and "$PROGRAM" eq "CROND"
    };
    parser { app-bigip-postfilter() };
};

block parser app-bigip-postfilter() {
     channel {
        rewrite {
            r_set_splunk_dest_default(
                index('netops')
                source('f5:bigip')
                sourcetype('f5:bigip:$(lowercase ${PROGRAM})')
                vendor("f5")
                product('bigip')
                class('crond')
            );
        };
   };
};
```

in place of test in host use the host of bigip and it will work as expected

**Comment by Jo-Ng** [comment] 2023-01-10 05:46
Nope. With the conf given above, non of the F5 events show at all. It just goes missing.

During early stage when on boarding the F5. All F5 events showing as “vmware:esxlog:crond”

With the help from PS with below 3 configuration, 
Below the existing filter that in place (app-vps-f5_bigip.conf)
#/opt/sc4s/local/config/app-parsers/app-vps-f5_bigip.conf
#File name provided is a suggestion it must be globally unique

application app-vps-test-f5_bigip[sc4s-vps] {
filter {
        "${HOST}" eq "Test01" or
        "${HOST}" eq "Test02"
    };
    parser {
        p_set_netsource_fields(
            vendor('f5')
            product('bigip')
        );
    };
};


**From compliance_meta_by_source.conf**
filter f_override_f5_bigip {
   host("Test*" type(glob))
};

**From compliance_meta_by_source.csv**
f_vps_aruba_ap,.splunk.sourcetype,"aruba:syslog"
f_override_f5_bigip,.splunk.sourcetype,"f5:bigip:syslog"
f_override_f5_bigip,.splunk.source,"f5:bigip:syslog:sc4s"

Where it displayed as the 1st screenshot early “sc4s_product=vsphere” / sourctype=“vmware:esxlog:crond”

**Comment by rjha-splunk** [comment] 2023-01-10 05:55
It should go to netops index, it was tested with the pcap provided, i will reproduce the test with other conf files as
well

**Comment by rjha-splunk** [comment] 2023-01-10 10:49
I created the same environment with the same files as mentioned, it works as expected , try creating netops index and you will see the data there, else update  index below

```
r_set_splunk_dest_default(
                index('netops')
```

**Comment by Jo-Ng** [comment] 2023-01-10 15:13
Thanks for pointing the error. I have updated the index and it appeared working. It also showing more sourcetype compared to previous

f5:bigip:-tmsh
f5:bigip:crond
f5:bigip:crond
f5:bigip:mcpd
f5:bigip:run-parts(/etc/cron.hourly)
f5:bigip:snmpd
f5:bigip:sshd
f5:bigip:sshd(pam_audit)
f5:bigip:syslog

Question,
Is that a way that we could not do on the postfilter?
1)	Not hard code the host name on it?
2)	Ignore the line on the index(‘netops’) since our end already make use of splunk_metadata.csv for index changed ?
      application app-bigip-postfilter[sc4s-postfilter] {
 filter {
        host("test*" type(glob))
       and "$PROGRAM" eq "CROND"
    };
    parser { app-bigip-postfilter() };
};

block parser app-bigip-postfilter() {
     channel {
        rewrite {
            r_set_splunk_dest_default(
                index('netops')
                source('f5:bigip')
                sourcetype('f5:bigip:$(lowercase ${PROGRAM})')
                vendor("f5")
                product('bigip')
                class('crond')
            );
        };
   };
};

3)	May I know how you could simulate by make use of the PCAP and test on your environment? Is that anything that could share so that I could bring the issues from Production to Development for test?

**Comment by Jo-Ng** [comment] 2023-01-11 02:02
It seems like that some issues on the below 2 items. 
f5:bigip:-tmsh
f5:bigip:mcpd
Similar events but it reported as source=program:mcpd vs source-f5:bigip. this happend to tmsh too.
Please refer to the screenshot given on support case open early.
https://splunk.my.site.com/customer/s/case/5005a00002Nzd2uAAB/sc4s-f5-bigip-crond-events-wrongly-assigned-as-vmware

**Comment by rjha-splunk** [comment] 2023-01-11 06:38
This is different case and in my opinion support can help on that, i will close this issue for now, the message can be checked how it is parsing by analyzing the pcap message in wireshark ( statistics > conversation > select udp > follow stream) , echo the message in sc4s to see how its getting parsed.

For every message type pcap will be required to check , but as far as it looks like this is not supported type message and for that a new conf file will be required.

**Comment by rjha-splunk** [comment] 2023-01-11 10:12
Please open another issue for help related to other sourcetype(enhancement request)

**Closed** 2023-01-11 10:12 UTC
