### ISSUE TITLE
grouping-by / aggregate feature log loss

### ISSUE THREAD

**Issue by olivierpas** [splunk/splunk-connect-for-syslog#2364] opened 2024-03-06 12:18 UTC
**Was the issue replicated by support?**
No
**What is the sc4s version ?**
3.22.1
**Is there a pcap available?**
No
**Is the issue related to the environment of the customer or Software related issue?**
No
**Is it related to Data loss, please explain ?**
Protocol? Hardware specs?
Yes, i am using grouping-by and the sum of all "repetition" field is not equivalent if i change the timeout value from my rewriter.

**Last chance index/Fallback index?**
Yes
**Is the issue related to local customization?**
Yes
**Do we have all the default indexes created?**
Yes
**Describe the bug**

When i change the timeout from 60 to 180 it devide the _raw count and also the repetition sum by 3.
repetition field is calculate each time a log match.

![image](https://github.com/splunk/splunk-connect-for-syslog/assets/90622815/9f49fecb-cc21-4977-9044-151b2c18d68d)

**To Reproduce**
Change the timeout value

[app-dest-rewrite-pan_panos.conf.txt](https://github.com/splunk/splunk-connect-for-syslog/files/14508613/app-dest-rewrite-pan_panos.conf.txt)

**Comment by mstopa-splunk** [comment] 2024-03-08 10:46
hi @olivierpas if that's your custom parser and the problems is directly with the syslog-ng DSL we can help on the best effort basis. Please provide the minimal reproducible example

**Comment by olivierpas** [comment] 2024-03-08 12:38
Hello @mstopa-splunk , and thank you for your reponse. what do you need exacly ? logs are pan:traffic sourcetype basis ( Palo Alto)

**Comment by mstopa-splunk** [comment] 2024-03-08 14:24
@olivierpas I wondered if there was a way to recreate the error in my lab but let's start on your side.

So `count(raw)` != `sum(repetition)`.
But both correctly dropped to ~30% after 10:00, when you changed the timeout. This looks correct, so why is changing the timeout important for this case?

If the problem is that `count(raw)` != `sum(repetition)`, please send the same graph but by SC4S containers to make sure that all your SC4S instances include `app-dest-rewrite-paloalto_panos-d_fmt_hec_default`.

If the problem is about timeout, please explain

**Comment by olivierpas** [comment] 2024-03-08 16:40
@mstopa-splunk yes the config is the same on all SC4S instance.
The only issue is the difference of volume after the change of timeout value.
i was wrong with my first request.
The expecting result is to have the sum(total) more important than the count(_raw) value by changing the timeout from 60 to 180.
The goal is the aggregate similar logs, not loosing them.
![image](https://github.com/splunk/splunk-connect-for-syslog/assets/90622815/8d81c641-bf0e-4a60-ae76-94a0ac94e15e)

**Comment by mstopa-splunk** [comment] 2024-03-11 14:29
```
So your suggestion is that syslog-ng never release the aggregated log because the timeout is to high ?
```

Exactly. When you use my conf and script, but never do a break, syslog-ng aggregates forever. 
When you break the sending process, syslog-ng waits until timeout and only then releases the aggregated message. 
Every new event resets the timeout and this is confirmed in their docs.

**Comment by mstopa-splunk** [comment] 2024-03-12 09:10
all right, for now I'm closing this issue as solved

**Closed by mstopa-splunk** 2024-03-12 09:10 UTC
